### PR TITLE
Added ALB module

### PR DESCRIPTION
**Pull request by wooiliang**
This module is to create the ALB.

Module repo: https://github.com/imSold/IaC-ALB

### CODE REVIEW

**Comment by kamoljan** [comment]
@wooiliang let me create ALB repo under microservices-today for you

**Comment by wooiliang** [comment]
@kamoljan That will be nice! Thanks.

**Comment by kamoljan** [comment]
@wooiliang can you modify https://github.com/microservices-today/IaC-ALB and send PR?

**Comment by wooiliang** [comment]
sure @kamoljan

**Comment by wooiliang** [comment]
@kamoljan I have changed the repo URL to microservices-today. Please kindly check. Thanks!

**Comment by kamoljan** [comment]
@wooiliang thank you!

**Pull request merged**
